contact/urls.py
from django.conf.urls import patterns, url

from contact import views

urlpatterns = patterns('',
	url(r'^$', views.get_contact, name='index'),		
	url(r'^thanks/$', views.thanks, name='thanks'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^contact/', include('contact.urls', namespace = "contact")),
    url(r'^contact_form/', include('contact_form.urls', namespace = "contact_form")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views 

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

contact/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = "Published Recently"

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

contact/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.template import RequestContext

from contact.forms import ContactForm

def get_contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
		    subject = form.cleaned_data['subject']
		    message = form.cleaned_data['message']
		    sender = form.cleaned_data['sender']
		    cc_myself = form.cleaned_data['cc_myself']

		    message = "From " + sender + ":\n" + message

		    recipients = ['samibaig@gmail.com']
		    if cc_myself:
		        recipients.append(sender)

		    send_mail(subject, message, sender, recipients)
		    return HttpResponseRedirect('thanks/')
	else:
		form = ContactForm()
		
	return render_to_response("contact/index.html",  {'form': form,  }, context_instance = RequestContext(request))

def thanks(request):
    return HttpResponse("Thank you for sending your message. Your feedback is important to us.")

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.views import generic

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

contact/templates/contact/index.html
<center>
<img src="http://www.pediacities.com/wp-content/themes/pediacities/images/pediacities-logo-opt.png"/>
<h1> Contact Us </h1>
<form action="" method="POST">
    {% csrf_token %}
    
<div class="fieldWrapper">
    <label for="id_subject">Email Subject:</label><br/>
    {{ form.subject }}
</div>
<div class="fieldWrapper">
    <label for="id_sender">Your Email Address:</label><br/>
    {{ form.sender }}
</div>
<div class="fieldWrapper">
    <label for="id_message">Your Message:</label><br/>
    {{ form.message }}
</div>
<div class="fieldWrapper">
	{{ form.cc_myself }}
    <label for="id_cc_myself">Email me a copy of my message.</label>
</div>
    <input type="submit" value="Submit" />
</form>
</center>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
		<li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>